### ISSUE TITLE
'requests' is missing from requirements

### ISSUE THREAD

**Issue by xanarin** [meenmachine1/ghidra-manuals#1]
When running the tool in a venv on my Debian Bullseye machine, I got the following error:
```
$ ./get_ghidra_manuals.py /tmp/ghidra_10.3
Traceback (most recent call last):
  File "/home/wsloan/Documents/open-source/ghidra-manuals/./get_ghidra_manuals.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

My suggested fix would be to add `requests` to the `requirements.txt` file. I don't know if it would be better to pin it at a specific version or if generic `requests` is sufficient.

As a side note, thanks for this repo @meenmachine1! This saved me scouring the web for new PDFs for Ghidra 10.3

**Comment by meenmachine1** [comment]
Hey! Good catch. Just updated the repo  (https://github.com/meenmachine1/ghidra-manuals/commit/e8898862a4a753f858acbd80c8b52ef3f0207306) to add requests to the requirements and a few other things. 

Thank you!
